// <auto-generated />
namespace CafeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _31721 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_31721));
        
        string IMigrationMetadata.Id
        {
            get { return "202107311406077_31-7-21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
